apiVersion: v1
kind: Secret
metadata:
  name: ia-api-secrets
  namespace: renovai-api
type: Opaque
stringData:
  GEMINI_API_KEY: "PREENCHER"
  GROQ_API_KEY: "PREENCHER"
  QDRANT_API_KEY: "PREENCHER"
  DATABASE_URL: "postgresql://USUARIO:SENHA@HOST:5432/renovai?sslmode=require"
  QDRANT_URL: "https://HOST-QDRANT:6333"
  MONGODB_URI: "mongodb+srv://USUARIO:SENHA@HOST/mongo_dbrenovai"
